<!DOCTYPE html>
<html>
<head>
<title>Thu Sep 5, 2019 : #software (osg)</title>
</head>
<body>
<h3>Thu Sep 5, 2019 : #software (osg)</h3>
<span style="color: #43761b"><span style="font-size: small">(09:03:59)</span> <b>blin:</b></span> hey @bockjoo that package is available in osg35 development if you really want it<br/>
<span style="color: #43761b"><span style="font-size: small">(09:04:13)</span> <b>blin:</b></span> but iirc there were issues with 1.20.10<br/>
<span style="color: #7d414c"><span style="font-size: small">(09:31:26)</span> <b>bockjoo:</b></span> It's OK. I will use the one from other CEs for now. Thanks!<br/>
<span style="color: #b14cbc"><span style="font-size: small">(10:44:13)</span> <b>tmartin:</b></span> Anyone around that could help me out with a xrootd issue? About a week ago I started to get errors like this.<br/><br/><pre><br/>open(<a href="root://redirector.t2.ucsd.edu:1094//store/test/xrootd/T2_US_UCSD/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root">root://redirector.t2.ucsd.edu:1094//store/test/xrootd/T2_US_UCSD/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root</a>, flags=OpenFlags.READ, timeout=90)<br/>XRootDStatus.code=400 "[ERROR] Server responded with an error: [3010] Unable to open /store/test/xrootd/T2_US_UCSD/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root; permission denied"<br/></pre><br/><br/>This error is with a door with version 4.10.0.<br/><br/>On top of that I am seeing a lot of issues even reading files. I am not sure if they are related or not, but I can read fine generally from another system the only difference (I copied over the config from the working system) is the version I think, 4.9.1. Copies are just hanging.<br/><br/><pre><br/>190905 08:28:54 23101 alicelik.77:312@cmswn1969.fnal.gov XrootdResponse: sending err 3005: Unable to read /store/mc/RunIISummer16NanoAODv4/WJetsToLNu_HT-400To600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_Nano14Dec2018_102X_mcRun2_asymptotic_v6_ext1-v1/30000/BBAE8D6A-3EFF-7D49-B348-7307958CE4B4.root; unknown error 255<br/>hdfsPread: FSDataInputStream#read error:<br/>IOException: Filesystem closedjava.io.IOException: Filesystem closed<br/>        at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:860)<br/>        at org.apache.hadoop.hdfs.DFSInputStream.pread(DFSInputStream.java:1490)<br/>        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:1477)<br/>        at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:92)<br/>190905 08:28:54 20743 hdfs_Read: Unable to read /cms/phedex/store/data/Run2018D/EGamma/MINIAOD/22Jan2019-v2/60001/9BA56F79-CC92-E543-A1C4-D581437BD8CC.root; Unknown error 255<br/>hdfsPread: FSDataInputStream#read error:<br/>IOException: Filesystem closedjava.io.IOException: Filesystem closed<br/>        at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:860)<br/>        at org.apache.hadoop.hdfs.DFSInputStream.pread(DFSInputStream.java:1490)<br/>        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:1477)<br/>        at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:92)<br/>190905 08:28:54 21568 hdfs_Read: Unable to read /cms/phedex/store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/321/755/00000/CA6B5EEB-3FAB-E811-95C4-FA163E28675E.root; Unknown error 255<br/>190905 08:28:54 21568 ofs_readv: cndrusr2.2482:874@bwforcluster-nat3.fun.uni-freiburg.de Unable to readv /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/321/755/00000/CA6B5EEB-3FAB-E811-95C4-FA163E28675E.root; unknown error 255<br/>190905 08:28:54 21568 cndrusr2.2482:874@bwforcluster-nat3.fun.uni-freiburg.de XrootdResponse: sending err 3005: Unable to readv /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/321/755/00000/CA6B5EEB-3FAB-E811-95C4-FA163E28675E.root; unknown error 255<br/>190905 08:28:54 20390 cms_Finder: Lost contact with cmsd via /var/run/xrootd/server/.olb/olbd.admin<br/></pre><br/>
<span style="color: #e06b56"><span style="font-size: small">(10:50:03)</span> <b>jthiltges:</b></span> We saw the HDFS "Unknown error 255", and it seemed to go away after upgrading to v4.10. I suspect it was caused by memory corruption fixed in this PR: <a href="https://github.com/xrootd/xrootd/pull/1012">https://github.com/xrootd/xrootd/pull/1012</a><br/><br/>Regarding the permission denied on the v4.10 server, I've usually seen that when a plugin isn't loaded due to a version mismatch. But that wouldn't cause it to stop working out of the blue.<br/>
<span style="color: #b14cbc"><span style="font-size: small">(10:51:45)</span> <b>tmartin:</b></span> You mean like the hdfs plugin? Ok, well I just brought the whole thing back to the latest.<br/>
<span style="color: #b14cbc"><span style="font-size: small">(10:52:18)</span> <b>tmartin:</b></span> apparently there was an update to xrootd-hdfs.x86_64<br/>
<span style="color: #e06b56"><span style="font-size: small">(10:55:01)</span> <b>jthiltges:</b></span> I've been burned by not updating xrootd-lcmaps (I think.). The version mismatch errors are really easy to overlook in the flood of output on startup. Pattern should look like this:<br/><pre>Plugin:  version XrdAccTest v4.8.99 is using  version XrdAcc v4.9.1 which is incompatible!</pre><br/>
<span style="color: #b14cbc"><span style="font-size: small">(10:55:51)</span> <b>tmartin:</b></span> Well it is possible that the issue was introduced a couple weeks ago, but it did not become crippling until the last couple days. So the timing could be off.<br/><pre><br/> xrootd-hdfs.x86_64 0:2.1.6-1.osg34.el7                                   xrootd-lcmaps.x86_64 0:1.7.4-2.osg34.el7<br/>  xrootd-scitokens.x86_64 0:1.0.0-1.1.osg34.el7<br/></pre><br/><br/>That is what updated, so you might be on to something, I hope. :slightly_smiling_face:<br/>
<span style="color: #43761b"><span style="font-size: small">(11:00:15)</span> <b>blin:</b></span> the update to xrootd-hdfs was really minimal<br/>
<span style="color: #43761b"><span style="font-size: small">(11:00:30)</span> <b>blin:</b></span> it just added a default config file to <tt>/etc/xrootd/config.d/</tt><br/>
<span style="color: #43761b"><span style="font-size: small">(11:01:01)</span> <b>blin:</b></span> though it could fix your problem depending on what version you were running previously<br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:02:03)</span> <b>tmartin:</b></span> This system I think is still broken.<br/><br/><pre><br/>xrootd-selinux-4.10.0-1.osg34.el7.noarch<br/>xrootd-client-libs-4.10.0-1.osg34.el7.x86_64<br/>xrootd-scitokens-0.6.0-3.osg34.el7.x86_64<br/>xrootd-server-libs-4.10.0-1.osg34.el7.x86_64<br/>xrootd-hdfs-2.1.4-1.osg34.el7.x86_64<br/>gfal2-plugin-xrootd-2.16.3-1.el7.x86_64<br/>xrootd-server-4.10.0-1.osg34.el7.x86_64<br/>python2-xrootd-4.10.0-1.osg34.el7.x86_64<br/>xrootd-libs-4.10.0-1.osg34.el7.x86_64<br/>xrootd-cmstfc-1.5.2-3.osg34.el7.x86_64<br/>xrootd-4.10.0-1.osg34.el7.x86_64<br/>xrootd-lcmaps-1.7.0-1.1.osg34.el7.x86_64<br/>xrootd-client-4.10.0-1.osg34.el7.x86_64<br/></pre><br/><br/>This might be working??<br/><br/><pre><br/>xrootd-server-4.10.0-1.osg34.el7.x86_64<br/>xrootd-cmstfc-1.5.1-11.osg34.el7.x86_64<br/>xrootd-lcmaps-1.7.4-2.osg34.el7.x86_64<br/>xrootd-libs-4.10.0-1.osg34.el7.x86_64<br/>xrootd-scitokens-1.0.0-1.1.osg34.el7.x86_64<br/>xrootd-4.10.0-1.osg34.el7.x86_64<br/>xrootd-scitokens-debuginfo-0.6.0-3.osg34.el7.x86_64<br/>xrootd-server-libs-4.10.0-1.osg34.el7.x86_64<br/>xrootd-client-4.10.0-1.osg34.el7.x86_64<br/>gfal2-plugin-xrootd-2.16.3-1.el7.x86_64<br/>xrootd-hdfs-2.1.6-1.osg34.el7.x86_64<br/>python2-xrootd-4.10.0-1.osg34.el7.x86_64<br/>xrootd-selinux-4.10.0-1.osg34.el7.noarch<br/>xrootd-client-libs-4.10.0-1.osg34.el7.x86_64<br/></pre><br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:03:33)</span> <b>tmartin:</b></span> However I am only running this system connected to the redirector, and it seems to have the most success.<br/><br/><pre><br/>xrootd-libs-4.9.1-1.osg34.el7.x86_64<br/>xrootd-lcmaps-1.7.0-1.1.osg34.el7.x86_64<br/>xrootd-server-4.9.1-1.osg34.el7.x86_64<br/>xrootd-selinux-4.9.1-1.osg34.el7.noarch<br/>xrootd-4.9.1-1.osg34.el7.x86_64<br/>xrootd-hdfs-2.1.4-1.osg34.el7.x86_64<br/>gfal2-plugin-xrootd-2.16.1-1.el7.x86_64<br/>xrootd-cmstfc-1.5.2-1.osg34.el7.x86_64<br/>xrootd-server-libs-4.9.1-1.osg34.el7.x86_64<br/>xrootd-client-libs-4.9.1-1.osg34.el7.x86_64<br/>python2-xrootd-4.9.1-1.osg34.el7.x86_64<br/>xrootd-client-4.9.1-1.osg34.el7.x86_64<br/></pre><br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:06:04)</span> <b>tmartin:</b></span> Really the only big cluster change I have made is more nodes to hadoop in the past week.<br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:06:21)</span> <b>tmartin:</b></span> but the errors started mostly yesterday.<br/>
<span style="color: #9e3997"><span style="font-size: small">(11:10:05)</span> <b>bbockelm:</b></span> <pre><br/>IOException: Filesystem closedjava.io.IOException: Filesystem closed<br/></pre><br/>That means that something went "pop" in the JVM.  I don't think it's recoverable.<br/>
<span style="color: #9e3997"><span style="font-size: small">(11:10:09)</span> <b>bbockelm:</b></span> You need to restart the server.<br/>
<span style="color: #9e3997"><span style="font-size: small">(11:10:19)</span> <b>bbockelm:</b></span> (the process, not the host itself)<br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:11:07)</span> <b>tmartin:</b></span> Ok, well it seems to keep happening....<br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:11:37)</span> <b>tmartin:</b></span> There was a java update in the last yum though...<br/>
<span style="color: #9e3997"><span style="font-size: small">(11:12:32)</span> <b>bbockelm:</b></span> so it comes back after a restart?<br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:13:19)</span> <b>tmartin:</b></span> It seemed to, but then hung, it is hard to know as I was not looking for an error of that type, ie a hung process that needs restarting.<br/>
<span style="color: #9e3997"><span style="font-size: small">(11:13:31)</span> <b>bbockelm:</b></span> In that case, I would look for the first error before the "Filesystem closed".<br/>
<span style="color: #9e3997"><span style="font-size: small">(11:14:24)</span> <b>bbockelm:</b></span> I.e., there may be a fatal error _then_ you get "Filesystem closed" consistently after that.<br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:14:33)</span> <b>tmartin:</b></span> <pre><br/>INFO in AuthzKey: Returning '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ktaeun/CN=825103/CN=Taeun Kwon::cms:/cms,::' of length 87 as key.<br/>190905 08:28:54 23467 XrootdXeq: nobody.349:460@calnat-8.ultralight.org pub IPv4 login as uscms<br/>190905 08:28:54 23467 nobody.349:460@calnat-8.ultralight.org XrootdProtocol: endsess 20283:140.13362<br/>190905 08:28:54 23467 nobody.349:460@calnat-8.ultralight.org XrootdProtocol: endsess 20283:140.13362 rc=-3 (No such process)<br/>190905 08:28:54 23467 acc_Audit: nobody.349:460@calnat-8.ultralight.org grant gsi uscms@[::ffff:128.227.78.130] read /store/data/Run2018D/ParkingBPH2/M<br/>INIAOD/05May2019promptD-v1/260000/92F40F5B-2BD5-7B4C-B199-07727A451747.root<br/>Resulting PFN: /cms/phedex/store/data/Run2018D/ParkingBPH2/MINIAOD/05May2019promptD-v1/260000/92F40F5B-2BD5-7B4C-B199-07727A451747.root<br/>File we will access: /cms/phedex/store/data/Run2018D/ParkingBPH2/MINIAOD/05May2019promptD-v1/260000/92F40F5B-2BD5-7B4C-B199-07727A451747.root<br/>hdfsPread: FSDataInputStream#read error:<br/>IOException: Filesystem closedjava.io.IOException: Filesystem closed<br/>        at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:860)<br/>        at org.apache.hadoop.hdfs.DFSInputStream.pread(DFSInputStream.java:1490)<br/>        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:1477)<br/>        at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:92)<br/>190905 08:28:54 15773 hdfs_Read: Unable to read /cms/phedex/store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/321/732/00000/3A0D79B1-BCAA-E811-B974-FA163E24F9E5.root; Unknown error 255<br/>190905 08:28:54 15773 ofs_read: cndrusr6.2482:811@bwforcluster-nat3.fun.uni-freiburg.de Unable to read /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/321/732/00000/3A0D79B1-BCAA-E811-B974-FA163E24F9E5.root; unknown error 255<br/>190905 08:28:54 15773 cndrusr6.2482:811@bwforcluster-nat3.fun.uni-freiburg.de XrootdResponse: sending err 3005: Unable to read /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/321/732/00000/3A0D79B1-BCAA-E811-B974-FA163E24F9E5.root; unknown error 255<br/></pre><br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:14:45)</span> <b>tmartin:</b></span> That is the first instance<br/>
<span style="color: #9e3997"><span style="font-size: small">(11:14:45)</span> <b>bbockelm:</b></span> any other errors prior to that?<br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:15:18)</span> <b>tmartin:</b></span> <pre><br/> bytes used of 701262 read (2.06%)<br/>19/09/05 03:57:11 WARN hdfs.BlockReaderFactory: I/O error constructing remote block reader.<br/>java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/169.228.130.132:42214 remote=/169.228.131.152:50010]<br/>        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)<br/>        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)<br/>        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)<br/>        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)<br/></pre><br/>
<span style="color: #9e3997"><span style="font-size: small">(11:15:44)</span> <b>bbockelm:</b></span> any out-of-memory errors in the log?<br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:16:27)</span> <b>tmartin:</b></span> The word memory does not occur, not sure if that is definitive<br/>
<span style="color: #e06b56"><span style="font-size: small">(11:19:28)</span> <b>jthiltges:</b></span> If this is happening on v4.9, I'm blaming that memory corruption bug in checksuming (causing the JVM to flip out).<br/>This sounds similar to the conversation with Paul Millar on smoketest failures at Nebraska a few months back. @bbockelm<br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:20:59)</span> <b>tmartin:</b></span> 4.9 is the only one that is working, the 4.10 systems are the ones I have to shutdown to get me green.<br/>
<span style="color: #e06b56"><span style="font-size: small">(11:21:43)</span> <b>jthiltges:</b></span> To clarify, 4.9 is working, with occasional "Unknown error 255", and 4.10 is entirely broken?<br/>
<span style="color: #b14cbc"><span style="font-size: small">(11:22:21)</span> <b>tmartin:</b></span> No errors with 4.9, 4.10 has two issues, one is auth and the other is the Unknown 255<br/>
<span style="color: #e06b56"><span style="font-size: small">(11:22:46)</span> <b>jthiltges:</b></span> Oof. Gotcha.<br/>
<span style="color: #e06b56"><span style="font-size: small">(12:13:47)</span> <b>jthiltges:</b></span> I updated an xrootd v4.10 server to the latest packages (included xrootd-hdfs, xrootd-lcmaps, and JVM updates).<br/>There were a handful of the <tt>Unknown error 255</tt> shortly after updating, but everything seems OK after a restart of the xrootd service.<br/>
<span style="color: #b14cbc"><span style="font-size: small">(12:25:11)</span> <b>tmartin:</b></span> Ok, I am going to turn off the old one, which has had green tests for the last few hours, and enable the new one, which also works for my users for writes, the older door does not.<br/>
<span style="color: #e06b56"><span style="font-size: small">(13:29:32)</span> <b>jthiltges:</b></span> For the OSG yum repo mirrors, how frequently should they be rsync'ing from the master?<br/>Nebraska is hourly, for what it's worth.<br/>
<span style="color: #c386df"><span style="font-size: small">(13:30:58)</span> <b>matyas:</b></span> hourly is OK, half-hourly would be better<br/>
<span style="color: #e06b56"><span style="font-size: small">(13:31:38)</span> <b>jthiltges:</b></span> Sounds good, I'll change it. Could the UChicago folks check their crontab?<br/>
<span style="color: #43761b"><span style="font-size: small">(13:36:40)</span> <b>blin:</b></span> @jlstephen @djordan66 ^^<br/>
<span style="color: #ea2977"><span style="font-size: small">(13:38:38)</span> <b>jlstephen:</b></span> i think it's once a week for uchicago, but i can check in a bit<br/>
<span style="color: #43761b"><span style="font-size: small">(13:42:26)</span> <b>blin:</b></span> thanks!<br/>
<span style="color: #ea2977"><span style="font-size: small">(14:17:19)</span> <b>jlstephen:</b></span> uchicago runs every six hours<br/>
<span style="color: #7d414c"><span style="font-size: small">(14:46:54)</span> <b>bockjoo:</b></span> Where does /cvmfs/oasis.opensciencegrid.org/mis/vodata/vomses come from?<br/>
<span style="color: #43761b"><span style="font-size: small">(14:48:56)</span> <b>blin:</b></span> we unpack it from our <tt>vo-client</tt> packaging<br/>
<span style="color: #43761b"><span style="font-size: small">(14:49:05)</span> <b>blin:</b></span> i believe this is done nightly @matyas @tim.theisen<br/>
<span style="color: #c386df"><span style="font-size: small">(14:51:04)</span> <b>matyas:</b></span> every 6 hours<br/>
</body>
</html>
